name: Glauncher
version: '1.0'
main: me.pink.glauncher.Glauncher
api-version: '1.20'
load: STARTUP
depend:
  - NBTAPI

commands:
  gl:
    description: Основная команда плагина
    usage: /gl <subcommand>
    aliases: [glauncher]

subcommands:
  give:
    description: Выдает предмет с уникальным NBT тэгом
    usage: /gl give <launcher/grenade> <player>
